version: '3'

services:
  olympus_api:
    container_name: rag
    image: demoday
    network_mode: "host"
    environment:
      - OPENAI_API_KEY
      - WANDB_API_KEY
    # command: chainlit run src/streamlit_v4.py -h
    restart: always


